run:
  dir: logs/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}/run/${model.name}/mix_${model.distrib.num_mixtures}/flow_${model.flow.layers}_${model.flow.nl.name}_${model.flow.length}/
sweep:
  dir: logs/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}/multirun/${model.name}/mix_${model.distrib.num_mixtures}/flow_${model.flow.layers}_${model.flow.nl.name}_${model.flow.length}/
  # ${now:%Y-%m-%d_%H-%M-%S}
  # subdir: ${hydra.job.num}